apiVersion: v1
kind: Secret
metadata:
  name: msvc-usuarios
type: Opaque
data:
  DB_USERNAME: cm9vdA==
  DB_PASSWORD: YWRtaW4xMjM=
---
apiVersion: v1
kind: Secret
metadata:
  name: msvc-cursos
type: Opaque
data:
  DB_USERNAME: cG9zdGdyZXM=
  DB_PASSWORD: YWRtaW4xMjM=
