input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  if [service_name] {
    mutate {
      add_field => { "[@metadata][index_name]" => "%{service_name}" }
      lowercase => [ "[@metadata][index_name]" ]
    }
  } else {
    mutate {
      add_field => { "[@metadata][index_name]" => "unknown-service" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "msvc-logs-%{[@metadata][index_name]}-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
